apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: redis
  namespace: letflow
spec:
  routes:
    - match: HostSNI(`*`)
      services:
        - name: redis-master
          port: 6379
